DROP TABLE IF EXISTS TASKS;
CREATE TABLE TASKS(
  ID INT PRIMARY KEY AUTO_INCREMENT,
  CREATION_TIMESTAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CLIENT_ID INT NOT NULL,
  NAME VARCHAR(128) NOT NULL,
  STATUS VARCHAR(16) DEFAULT 'NEW',
  LAST_UPDATE_TIMESTAMP TIMESTAMP,
  FILE_URL VARCHAR(256)
);

INSERT INTO TASKS(CLIENT_ID, NAME) VALUES (1, 'photo');
INSERT INTO TASKS(CLIENT_ID, NAME) VALUES (2, 'photo');

DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS(
  USER_ID INT PRIMARY KEY AUTO_INCREMENT,
  NAME VARCHAR(128) NOT NULL UNIQUE,
  STATUS VARCHAR(16) NOT NULL DEFAULT 'LOGOUT'
);

INSERT INTO USERS(NAME) VALUES ('Marian');
