DROP TABLE IF EXISTS TASKS;
CREATE TABLE TASKS(ID INT PRIMARY KEY, TIMESTAMP TIMESTAMP, CLIENT_ID INT, NAME VARCHAR(128), STATUS VARCHAR(16));

INSERT INTO TASKS VALUES (1, current_timestamp(), 1, 'photo', 'done');
INSERT INTO TASKS VALUES (2, current_timestamp(), 1, 'photo', 'new');
